"""Phase 4b: leakage-safe train/holdout cohort construction
(`docs/model_design.md`'s split strategy).

Two *separate* full pipeline runs -- different `population_seed`, different
outcome-noise seeds -- rather than a row split within one population.

Precisely what this does and does not vary (`docs/model_design.md`'s split-
strategy section has the full explanation): `raking.rake`/`integerize` are
deterministic given the same target set, so `geography`, `low_ses`,
`first_nations`, and `seifa_decile` come out identical between any two
cohorts built from the same target set -- that is calibration working as
intended, not a leak. What a cohort-based split needs to vary, and does, is
the stochastic part: the four independently-assigned attributes, the
shared latent risk draw, and every outcome/behavioural signal. Both cohorts
are generated by the *same* target-driven calibration process
(`outcomes.calibrate_anchors` re-solves fresh for whatever population and
noise draw it is given): verified directly (not assumed) that train and
holdout land within ~0.5pp of each other and of the 82.91% published target
-- anchors are a property of the data-generating process calibrated against
the published targets, not something fit on train and carried over to
holdout the way a model's parameters would be.
"""

from __future__ import annotations

import pandas as pd
from equitylens_synthetic.outcomes import assign_retention_outcomes, generate_latent_risk
from equitylens_synthetic.population import build_raked_population

from equitylens_risk.features import (
    CENSUS_FEATURE_COLUMNS,
    build_census_feature_table,
    generate_census_engagement_signal,
)

RETENTION_CONNECTION_STRENGTH = 0.7
CENSUS_CONNECTION_STRENGTH = 0.4

# Distinct seeds per cohort, per component (population raking, shared latent
# risk, retention-outcome noise, census-signal noise) -- reusing any of a
# cohort's own seeds across cohorts would partially re-couple the two
# "independent" cohorts this split is meant to keep apart.
_TRAIN_SEEDS = {
    "population_seed": 42,
    "latent_seed": 100,
    "outcome_seed": 42,
    "census_seed": 900,
}
_HOLDOUT_SEEDS = {
    "population_seed": 777,
    "latent_seed": 777_100,
    "outcome_seed": 777,
    "census_seed": 777_900,
}


def build_cohort(
    target_set: dict,
    n_students: int,
    *,
    institution_id: str = "acu",
    population_seed: int,
    latent_seed: int,
    outcome_seed: int,
    census_seed: int,
) -> pd.DataFrame:
    """One full synthetic cohort: raked population -> retention outcome
    (shared-latent-risk-linked) -> census-dated engagement signal."""

    population, _convergence, _integerization = build_raked_population(
        target_set, n_students, institution_id=institution_id, seed=population_seed
    )
    latent_risk = generate_latent_risk(len(population), seed=latent_seed)
    population, _retention_convergence = assign_retention_outcomes(
        population,
        target_set,
        institution_id=institution_id,
        connection_strength=RETENTION_CONNECTION_STRENGTH,
        shared_latent_risk=latent_risk,
        seed=outcome_seed,
    )
    population["census_engagement_score"] = generate_census_engagement_signal(
        population,
        latent_risk,
        connection_strength=CENSUS_CONNECTION_STRENGTH,
        seed=census_seed,
    )
    return population


def build_train_holdout(
    target_set: dict,
    n_students: int = 20000,
    institution_id: str = "acu",
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """`docs/model_design.md`'s cohort-based split: train uses this
    project's standing default seed (42), holdout uses an entirely
    different one (777) -- a distinct simulated cohort, not a subsample."""

    train = build_cohort(target_set, n_students, institution_id=institution_id, **_TRAIN_SEEDS)
    holdout = build_cohort(target_set, n_students, institution_id=institution_id, **_HOLDOUT_SEEDS)
    return train, holdout


def features_and_labels(population: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    """Census-safe feature table plus the risk label (1 = attrited, the
    class Phase 4d's triage cares about identifying).

    Asserts the feature table exposes *exactly* the allow-listed columns --
    a guard against a future refactor accidentally widening the feature set
    past what `docs/model_design.md` reviewed as leakage-safe.
    """

    features = build_census_feature_table(population)
    assert list(features.columns) == list(CENSUS_FEATURE_COLUMNS), (
        "feature table must expose exactly the allow-listed census columns -- "
        "docs/model_design.md's leakage-safety guarantee depends on this"
    )
    labels = (~population["retained"]).astype(int)
    return features, labels
